### ISSUE TITLE
[Container] java.lang.ClassNotFoundException: java.beans.PropertyChangeEvent

### ISSUE THREAD

**Issue by MartinX3** [zyclonite/nassh-relay#20]
I just wanted to try the image `docker.io/zyclonite/nassh-relay:1.1.29`
**[1.1.28](https://github.com/zyclonite/nassh-relay/releases/tag/1.1.28) works.**

It results in:
```bash
Exception in thread "main" java.lang.NoClassDefFoundError: java/beans/PropertyChangeEvent
        at org.apache.logging.log4j.core.LoggerContext.updateLoggers(LoggerContext.java:747)
        at org.apache.logging.log4j.core.LoggerContext.updateLoggers(LoggerContext.java:734)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:628)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        at io.vertx.core.logging.SLF4JLogDelegate.<init>(SLF4JLogDelegate.java:37)
        at io.vertx.core.logging.SLF4JLogDelegateFactory.createDelegate(SLF4JLogDelegateFactory.java:49)
        at io.vertx.core.logging.LoggerFactory.<clinit>(LoggerFactory.java:36)
        at io.vertx.core.impl.logging.LoggerFactory.getLogger(LoggerFactory.java:26)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:46)
        at io.vertx.core.impl.launcher.commands.BareCommand.<init>(BareCommand.java:48)
        at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:36)
        at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:60)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:179)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:234)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
        at io.vertx.core.Launcher.main(Launcher.java:45)
Caused by: java.lang.ClassNotFoundException: java.beans.PropertyChangeEvent
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 27 more
```

According to the internet it gets fixed by `--add-modules java.xml,java.sql,java.prefs,java.desktop` as vm arguments.
https://stackoverflow.com/questions/57955837/java-11-java-beans-propertychangelistener

**Comment by zyclonite** [comment]
i tried to stick to the log4j version dictated by vertx, maybe that's the issue

i rolled back up to version 2.20.0 now, please give version 1.1.30 a try

**Comment by MartinX3** [comment]
Thank you! :)
