### ISSUE TITLE
Null pointer exception when Google Authentication enabled

### ISSUE THREAD

**Issue by chazlever** [zyclonite/nassh-relay#8]
After enabling Google Authentication, I get a null pointer exception upon authentication with Google. This failure prevents me from connecting via the relay. Here's the output I receive from the console logs:

```
20:34:07.138 [vert.x-eventloop-thread-0]      INFO  n.z.n.MainVerticle - nassh-relay listening on port 8022                                    
20:34:07.149 [vert.x-eventloop-thread-1]      INFO  i.v.c.i.l.c.VertxIsolatedDeployer - Succeeded in deploying verticle                        
20:34:18.002 [vert.x-eventloop-thread-0]      INFO  n.z.n.h.CookiePostHandler - Google User: id: 104796568810369987670 email: null domain: null
logged in
20:34:19.105 [vert.x-eventloop-thread-0]      ERROR n.z.n.h.ProxyHandler - NULL                                                                
java.lang.NullPointerException: null
        at net.zyclonite.nassh.util.AccessHelper.checkAccess(AccessHelper.java:57)                                                             
        at net.zyclonite.nassh.util.AccessHelper.isHostAllowed(AccessHelper.java:37)                                                           
        at net.zyclonite.nassh.handler.ProxyHandler.lambda$handle$0(ProxyHandler.java:89)                                                      
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)                                                       
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                     
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                               
        at java.lang.Thread.run(Thread.java:748)
```

Authentication fails to get an e-mail or domain, and the `checkAccess` looks like it's throwing a NullPointerException as a result. It looks like the code checks for null values, but there's still a failure happening somewhere in there. I've currently tried versions 1.0.6 and 1.0.5 of the relay.

**Comment by chazlever** [comment]
Ah, I did remove the whitelist section from the JSON configuration before enabling Google Authentication. It appears _that_ is what caused the null pointer exception and not oauth having null values for e-mail and domain. Upon re-adding the whitelist section, I'm no longer getting the null pointer exception and everything seems to be working as expected.

Looks like https://github.com/zyclonite/nassh-relay/commit/457f367dc25610bfc3b3b1c392a8befbadae3872 should fix this issue in the future. Thanks for adding a fix!
